on: [push, pull_request]
name: Main
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: OSKAR-PHP-CS-Fixer
      uses: OskarStark/php-cs-fixer-ga@3.2.1
